bigdatagenomics/cannoli

- src/main/scala/org/bdgenomics/cannoli/Freebayes.scala
per https://github.com/bigdatagenomics/adam/pull/1375
> SupportedHeaderLines renamed to DefaultHeaderLines

- src/main/scala/org/bdgenomics/cannoli/Bowtie.scala
- src/main/scala/org/bdgenomics/cannoli/Bowtie2.scala
- src/main/scala/org/bdgenomics/cannoli/Bwa.scala
- src/main/scala/org/bdgenomics/cannoli/Cannoli.scala
- src/main/scala/org/bdgenomics/cannoli/Freebayes.scala
- src/main/scala/org/bdgenomics/cannoli/SnpEff.scala
- src/main/scala/org/bdgenomics/cannoli/Tee.scala
Specified a default value for the path argument and added Docker arguments to Freebayes and SnpEff.
@fnothaft ping to review
> Add Docker arguments to Freebayes and SnpEff.

- src/main/scala/org/bdgenomics/cannoli/Bwa.scala
- src/main/scala/org/bdgenomics/cannoli/util/QuerynameGrouper.scala
- src/main/scala/org/bdgenomics/cannoli/util/QuerynameGroupingIterator.scala
- src/test/scala/org/bdgenomics/cannoli/util/QuerynameGroupingIteratorSuite.scala
> [CANNOLI-4] Add ability to save Fragments from BWA.

- pom.xml
> [CANNOLI-16] Update ADAM dependency version to 0.22.0

- pom.xml
- scripts/format-source
- scripts/jenkins-test
I've set up Jenkins, will still need to set up coveralls after the move.
> Prep for move to bigdatagenomics org

- pom.xml
> Disable incremental mode in the Scala build.

- src/main/scala/org/bdgenomics/cannoli/Bowtie2.scala
> Use --interleaved for bowtie2

- pom.xml
> [CANNOLI-46] Move adam-cli to provided scope.

- pom.xml
- src/main/scala/org/bdgenomics/cannoli/Bedtools.scala
- src/main/scala/org/bdgenomics/cannoli/Bowtie.scala
- src/main/scala/org/bdgenomics/cannoli/Bowtie2.scala
- src/main/scala/org/bdgenomics/cannoli/Bwa.scala
- src/main/scala/org/bdgenomics/cannoli/Freebayes.scala
- src/main/scala/org/bdgenomics/cannoli/SnpEff.scala
- src/main/scala/org/bdgenomics/cannoli/util/QuerynameGrouper.scala
Jenkins build will fail due to https://github.com/bigdatagenomics/adam/issues/1578
> Update adam dependency version to 0.23.0-SNAPSHOT.

- src/main/scala/org/bdgenomics/cannoli/Bwa.scala
> [CANNOLI-28] Allow docker command to be specified.

- src/main/scala/org/bdgenomics/cannoli/Cannoli.scala
- src/main/scala/org/bdgenomics/cannoli/InterleaveFastq.scala
- src/test/scala/org/bdgenomics/cannoli/InterleaveFastqSuite.scala
> [CANNOLI-51] Rename FastqInterleaver --> InterleaveFastq

- src/main/scala/org/bdgenomics/cannoli/Cannoli.scala
- src/main/scala/org/bdgenomics/cannoli/SampleReads.scala
I've found this useful for testing but not sure it is worth having in the repo.
> Adding sample reads tool.

- cli/src/main/scala/org/bdgenomics/cannoli/cli/SnpEff.scala
> [CANNOLI-83] Fix case for snpEff when using docker.

- cli/src/main/scala/org/bdgenomics/cannoli/cli/Freebayes.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/SnpEff.scala
> Fix compile error due to upstream 0.23.0-SNAPSHOT changes.

- cli/src/main/scala/org/bdgenomics/cannoli/cli/Bedtools.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/Bwa.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/Freebayes.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/SnpEff.scala
> [CANNOLI-76] Add --rm flag to docker run.

- pom.xml
> [CANNOLI-89] Bump ADAM dependency version to 0.23.0.

- cli/src/main/scala/org/bdgenomics/cannoli/cli/Cannoli.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/Vt.scala
> Adding wrapper for vt normalize.

- cli/src/main/scala/org/bdgenomics/cannoli/cli/Bcftools.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/Bedtools.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/Bowtie.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/Bowtie2.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/Bwa.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/Freebayes.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/Samtools.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/SnpEff.scala
Found and tested version-tagged Docker images in BioContainers for everything but `vt`.
> Use BioContainers Docker images with version tags by default.

- core/src/main/java/org/bdgenomics/cannoli/builder/CommandBuilder.java
> [CANNOLI-115] Fix javadoc error and warnings.

- pom.xml
> [CANNOLI-118] Update ADAM dependency version to 0.24.0.

- cli/src/main/scala/org/bdgenomics/cannoli/cli/BcftoolsNorm.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/Freebayes.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/SamtoolsMpileup.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/SnpEff.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/VtNormalize.scala
- pom.xml
> [CANNOLI-122] Support validation stringency in out formatters.

- cli/src/main/scala/org/bdgenomics/cannoli/cli/Cannoli.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/Vep.scala
> [CANNOLI-112]  Adding Ensembl Variant Effect Predictor (VEP) for variant annotation

- README.md
> [CANNOLI-128] Adding API documentation link and badge.

- cli/src/main/scala/org/bdgenomics/cannoli/cli/Cannoli.scala
- cli/src/test/scala/org/bdgenomics/cannoli/cli/CannoliSuite.scala
- core/src/main/scala/org/bdgenomics/cannoli/util/QuerynameGroupingIterator.scala
- core/src/test/scala/org/bdgenomics/cannoli/util/QuerynameGroupingIteratorSuite.scala
- pom.xml
> [CANNOLI-138] Update Cannoli per latest ADAM snapshot changes.

- pom.xml
> [CANNOLI-141] Update ADAM dependency to 0.25.0.

- pom.xml
> [CANNOLI-149] Update maven-surefire-plugin version to 3.0.0-M1.

- cli/src/main/scala/org/bdgenomics/cannoli/cli/BedtoolsIntersect.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/Bwa.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/SampleReads.scala
- core/src/main/scala/org/bdgenomics/cannoli/BcftoolsNorm.scala
- core/src/main/scala/org/bdgenomics/cannoli/BedtoolsIntersect.scala
- core/src/main/scala/org/bdgenomics/cannoli/Bowtie.scala
- core/src/main/scala/org/bdgenomics/cannoli/Bowtie2.scala
- core/src/main/scala/org/bdgenomics/cannoli/Bwa.scala
- core/src/main/scala/org/bdgenomics/cannoli/Cannoli.scala
- core/src/main/scala/org/bdgenomics/cannoli/Freebayes.scala
- core/src/main/scala/org/bdgenomics/cannoli/Minimap2.scala
- core/src/main/scala/org/bdgenomics/cannoli/SamtoolsMpileup.scala
- core/src/main/scala/org/bdgenomics/cannoli/SnpEff.scala
- core/src/main/scala/org/bdgenomics/cannoli/Vep.scala
- core/src/main/scala/org/bdgenomics/cannoli/VtNormalize.scala
- core/src/main/scala/org/bdgenomics/cannoli/util/QuerynameGrouper.scala
- core/src/main/scala/org/bdgenomics/cannoli/util/QuerynameGroupingIterator.scala
- core/src/test/scala/org/bdgenomics/cannoli/util/QuerynameGroupingIteratorSuite.scala
- pom.xml
> [CANNOLI-152] Bump ADAM dependency to version 0.26.0

- cli/src/main/scala/org/bdgenomics/cannoli/cli/BcftoolsMpileup.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/BcftoolsNorm.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/Cannoli.scala
- core/src/main/scala/org/bdgenomics/cannoli/BcftoolsMpileup.scala
- core/src/main/scala/org/bdgenomics/cannoli/Cannoli.scala
- core/src/main/scala/org/bdgenomics/cannoli/Minimap2.scala
> [CANNOLI-158] Adding bcftools mpileup.

- README.md
- core/src/main/scala/org/bdgenomics/cannoli/Freebayes.scala
> [CANNOLI-160] Rename -fasta_reference to -reference.

- core/src/main/scala/org/bdgenomics/cannoli/BedtoolsIntersect.scala
- core/src/main/scala/org/bdgenomics/cannoli/Bowtie2.scala
- core/src/main/scala/org/bdgenomics/cannoli/Bwa.scala
- core/src/main/scala/org/bdgenomics/cannoli/Freebayes.scala
- core/src/main/scala/org/bdgenomics/cannoli/SamtoolsMpileup.scala
- core/src/main/scala/org/bdgenomics/cannoli/SnpEff.scala
- core/src/main/scala/org/bdgenomics/cannoli/Vep.scala
> [CANNOLI-164] Update default docker images to latest stable versions

- assembly/pom.xml
- pom.xml
> [CANNOLI-167] Update ADAM dependency version to 0.27.0

- pom.xml
> [CANNOLI-172] Update ADAM dependency version to 0.28.0.

- cli/src/main/scala/org/bdgenomics/cannoli/cli/Cannoli.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/Star.scala
- core/src/main/scala/org/bdgenomics/cannoli/Cannoli.scala
- core/src/main/scala/org/bdgenomics/cannoli/Star.scala
> [CANNOLI-135] Adding STAR for alignment.

- cli/src/main/scala/org/bdgenomics/cannoli/cli/Cannoli.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/SingleEndBowtie2.scala
- core/src/main/scala/org/bdgenomics/cannoli/Cannoli.scala
- core/src/main/scala/org/bdgenomics/cannoli/SingleEndBowtie2.scala
> [CANNOLI-186] Adding single-end read bowtie2 functions

- README.md
- cli/src/main/scala/org/bdgenomics/cannoli/cli/BcftoolsCall.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/BcftoolsMpileup.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/BcftoolsNorm.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/BedtoolsIntersect.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/Blastn.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/Bowtie.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/Bowtie2.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/Bwa.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/Freebayes.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/Gem.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/MagicBlast.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/Minimap2.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/SamtoolsMpileup.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/SingleEndBowtie2.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/SnpEff.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/Star.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/Vep.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/VtNormalize.scala
- core/src/main/scala/org/bdgenomics/cannoli/Cannoli.scala
> [CANNOLI-193] Note dataset type in CLI command docs.

- pom.xml
> [CANNOLI-194] Add scaladoc to Maven javadoc artifacts

- pom.xml
> [CANNOLI-198] Bump ADAM dependency version to 0.29.0

- cli/src/main/scala/org/bdgenomics/cannoli/cli/Bwa.scala
- core/src/main/scala/org/bdgenomics/cannoli/BcftoolsMpileup.scala
- core/src/main/scala/org/bdgenomics/cannoli/Blastn.scala
- core/src/main/scala/org/bdgenomics/cannoli/Bowtie.scala
- core/src/main/scala/org/bdgenomics/cannoli/Bowtie2.scala
- core/src/main/scala/org/bdgenomics/cannoli/Bwa.scala
- core/src/main/scala/org/bdgenomics/cannoli/Cannoli.scala
- core/src/main/scala/org/bdgenomics/cannoli/Freebayes.scala
- core/src/main/scala/org/bdgenomics/cannoli/Gem.scala
- core/src/main/scala/org/bdgenomics/cannoli/MagicBlast.scala
- core/src/main/scala/org/bdgenomics/cannoli/Minimap2.scala
- core/src/main/scala/org/bdgenomics/cannoli/SamtoolsMpileup.scala
- core/src/main/scala/org/bdgenomics/cannoli/SingleEndBowtie2.scala
- core/src/main/scala/org/bdgenomics/cannoli/SingleEndStar.scala
- core/src/main/scala/org/bdgenomics/cannoli/Star.scala
- core/src/main/scala/org/bdgenomics/cannoli/util/QuerynameGrouper.scala
- core/src/main/scala/org/bdgenomics/cannoli/util/QuerynameGroupingIterator.scala
- core/src/test/scala/org/bdgenomics/cannoli/util/QuerynameGroupingIteratorSuite.scala
- pom.xml
> [CANNOLI-208] Update ADAM dependency version to 0.30.0

- README.md
> Remove Jenkins build status badge

- scripts/jenkins-test
> [CANNOLI-218] Add Jenkins support for Scala 2.12

- builder/src/main/java/org/bdgenomics/cannoli/builder/ContainerBuilder.java
- cli/src/main/scala/org/bdgenomics/cannoli/cli/Bwa.scala
- core/src/main/scala/org/bdgenomics/cannoli/Bwa.scala
- core/src/main/scala/org/bdgenomics/cannoli/ReadGroupArgs.scala
- core/src/main/scala/org/bdgenomics/cannoli/SingleEndStar.scala
> [CANNOLI-219] Allow to fully specify read groups for bwa

- core/src/main/scala/org/bdgenomics/cannoli/Blastn.scala
> [CANNOLI-226] Add -num_threads argument to BlastnArgs

- core/src/main/scala/org/bdgenomics/cannoli/Bowtie2.scala
- core/src/main/scala/org/bdgenomics/cannoli/SingleEndBowtie2.scala
> [CANNOLI-228] Bump Bowtie2 container image to version 2.3.5.1

- README.md
- cli/src/main/scala/org/bdgenomics/cannoli/cli/Cannoli.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/Snap.scala
- core/src/main/scala/org/bdgenomics/cannoli/Cannoli.scala
- core/src/main/scala/org/bdgenomics/cannoli/Snap.scala
> [CANNOLI-65] Add snap-aligner for alignment

- pom.xml
> [CANNOLI-233] Update ADAM dependency version to 0.31.0

- core/src/main/scala/org/bdgenomics/cannoli/BedtoolsIntersect.scala
- core/src/main/scala/org/bdgenomics/cannoli/Bowtie2.scala
- core/src/main/scala/org/bdgenomics/cannoli/SamtoolsMpileup.scala
- core/src/main/scala/org/bdgenomics/cannoli/SingleEndBowtie2.scala
- core/src/main/scala/org/bdgenomics/cannoli/Vep.scala
- core/src/main/scala/org/bdgenomics/cannoli/VtNormalize.scala
> [CANNOLI-241] Use biocontainers for vt; update container image versions

- pom.xml
> [CANNOLI-245] Update Spark dependency version to 2.4.6

- pom.xml
- scripts/jenkins-test
- scripts/move_to_spark_2.sh
- scripts/move_to_spark_3.sh
- scripts/release/release.sh
> [CANNOLI-216] Support Apache Spark 3.x in build

- pom.xml
> [CANNOLI-252] Update ADAM dependency version to 0.32.0

- assembly/pom.xml
- builder/pom.xml
- cli/pom.xml
- core/pom.xml
- distribution/pom.xml
- pom.xml
- scripts/jenkins-test
> [CANNOLI-248] Default build to Spark 3/Scala 2.12

- README.md
- cli/src/main/scala/org/bdgenomics/cannoli/cli/BwaMem2.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/Cannoli.scala
- core/src/main/scala/org/bdgenomics/cannoli/BwaMem2.scala
- core/src/main/scala/org/bdgenomics/cannoli/Cannoli.scala
> [CANNOLI-255] Add bwa-mem2 for aligning fragments

- README.md
- cli/src/main/scala/org/bdgenomics/cannoli/cli/BwaMem.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/Cannoli.scala
- core/src/main/scala/org/bdgenomics/cannoli/BwaMem.scala
- core/src/main/scala/org/bdgenomics/cannoli/Cannoli.scala
> [CANNOLI-257] Refactor Bwa class names to BwaMem

- pom.xml
- scripts/jenkins-test
- scripts/move_to_spark_2.sh
- scripts/move_to_spark_3.sh
> [CANNOLI-265] Update Spark dependency version to 3.0.1

- core/src/main/scala/org/bdgenomics/cannoli/Freebayes.scala
- core/src/main/scala/org/bdgenomics/cannoli/FreebayesHeaderLines.scala
> [CANNOLI-271] Add additional command line arguments, header lines for freebayes

- core/src/main/scala/org/bdgenomics/cannoli/Vep.scala
> [CANNOLI-244] Update --terms and other options for Ensembl VEP

- pom.xml
- scripts/jenkins-test
> [CANNOLI-278] Bump ADAM dependency version to 0.33.0

- scripts/release/release.sh
> [CANNOLI-284] Fix release script, default is Spark 3 Scala 2.12 profile

- assembly/pom.xml
- pom.xml
- scripts/jenkins-test
- scripts/move_to_scala_2.12.sh
- scripts/release/release.sh
Fixes #280, fixes #281, fixes #282, fixes #283
> Update build and release matrix

- cli/src/main/scala/org/bdgenomics/cannoli/cli/Bowtie.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/Bowtie2.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/BwaMem.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/BwaMem2.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/CramArgs.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/Freebayes.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/Gem.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/MagicBlast.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/Minimap2.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/SampleReads.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/SamtoolsMpileup.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/SingleEndBowtie2.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/SingleEndStar.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/Snap.scala
- cli/src/main/scala/org/bdgenomics/cannoli/cli/Star.scala
> [CANNOLI-287] Add CRAM reference argument for loading alignments and fragments

- .github/workflows/deploy.yml
- pom.xml
> [CANNOLI-292] Update Spark dependency version to 3.1.1

- pom.xml
> [CANNOLI-311] Update Spark dependency version to 3.1.2

- core/src/main/scala/org/bdgenomics/cannoli/Minimap2.scala
> Update minimap2 container image to version 2.20--h5bf99c6_0

- pom.xml
> [CANNOLI-321] Update ADAM dependency version to 0.36.0

- .github/workflows/ci.yml
- .github/workflows/deploy.yml
> Migrate Github Actions JDK from 'adopt' to 'temurin'

- pom.xml
> Update ADAM dependency version to 0.37.0

- README.md
> Use bwa singularity image for README example

- pom.xml
> Update ADAM dependency version to 1.0, spark to 3.2.1, hadoop to 3.3.3

- pom.xml
> Update Spark dependency version to 3.3.1

- pom.xml
> Update Spark dependency version to 3.3.2

- pom.xml
Fixes #372 
Might need to bump utils to latest snapshot as well?
> Update Apache Spark dependency version to 3.5.5
